spring.application.name=java-jooq

spring.datasource.url=jdbc:postgresql://localhost:5432/jooq_study
spring.datasource.username=dev
spring.datasource.password=dev123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jooq.sql-dialect=POSTGRES

server.error.include-message=always

